In [228]:
import pandas as pd

In [229]:
df = pd.read_csv('data.csv', header = [0, 1])
df.head()

  Unnamed: 0_level_0           Unnamed: 1_level_0 Unnamed: 2_level_0  \
                  Rk                       Player             Nation
0                  1      Declan Rice\Declan-Rice            eng ENG
1                  2                  Rodri\Rodri             es ESP
2                  3  Mateo Kovačić\Mateo-Kovacic             hr CRO
3                  4  Jonjo Shelvey\Jonjo-Shelvey            eng ENG
4                  5            Dan Burn\Dan-Burn            eng ENG

  Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0  \
                 Pos              Squad                Age               Born
0                 MF           West Ham                 21               1999
1                 MF    Manchester City                 24               1996
2                 MF            Chelsea                 26               1994
3                 MF      Newcastle Utd                 28               1992
4                 DF           Brighton                 28               1992

  Unnamed: 7_level_0 Touches          ... Carries                 Receiving  \
                 90s Touches Def Pen  ...    Prog 1/3 CPA Mis Dis      Targ
0               32.0    1800      99  ...     165  59   7  24  21      1271
1               30.5    3023     114  ...     192  47  10  18  22      2375
2               20.2    1934      26  ...     193  58   4  20  30      1711
3               29.1    1672      86  ...      71  24   1   7  12      1113
4               22.9    1516     115  ...      78  25   2  23  14      1036

                   Unnamed: 32_level_0
    Rec  Rec% Prog             Matches
0  1186  93.3   35             Matches
1  2315  97.5   38             Matches
2  1630  95.3   45             Matches
3  1055  94.8   26             Matches
4   920  88.8   43             Matches

[5 rows x 33 columns]

In [230]:
df.loc[: , ('Unnamed: 1_level_0', ['Player'])] = df.loc[: , ('Unnamed: 1_level_0', ['Player'])].replace(r".*\\", "", regex=True)

In [231]:
pos1 = df['Unnamed: 3_level_0']['Pos'].str.extract(r'(..)', expand=True)
pos2 = df['Unnamed: 3_level_0']['Pos'].str.extract(r'..(.*)', expand=True)
temp = pd.concat([pos1, pos2], axis = 1)
temp.columns = pd.MultiIndex.from_tuples([('Pos','Pos1'),('Pos','Pos2')])
df = df.drop(df.iloc[:, [3]], axis = 1)
df = pd.concat([df, temp], axis = 1)

In [234]:
df

    Unnamed: 0_level_0       Unnamed: 1_level_0 Unnamed: 2_level_0  \
                    Rk                   Player             Nation
0                    1              Declan-Rice            eng ENG
1                    2                    Rodri             es ESP
2                    3            Mateo-Kovacic             hr CRO
3                    4            Jonjo-Shelvey            eng ENG
4                    5                 Dan-Burn            eng ENG
..                 ...                      ...                ...
205                206             Nicolas-Pepe             ci CIV
206                207              Timo-Werner             de GER
207                208            Tammy-Abraham            eng ENG
208                209  Johann-Berg-Gudmundsson             is ISL
209                210         Emile-Smith-Rowe            eng ENG

    Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0  \
                 Squad                Age               Born
0             West Ham                 21               1999
1      Manchester City                 24               1996
2              Chelsea                 26               1994
3        Newcastle Utd                 28               1992
4             Brighton                 28               1992
..                 ...                ...                ...
205            Arsenal                 25               1995
206            Chelsea                 24               1996
207            Chelsea                 22               1997
208            Burnley                 29               1990
209            Arsenal                 20               2000

    Unnamed: 7_level_0 Touches                  ... Carries         Receiving  \
                   90s Touches Def Pen Def 3rd  ...     CPA Mis Dis      Targ
0                 32.0    1800      99     508  ...       7  24  21      1271
1                 30.5    3023     114     635  ...      10  18  22      2375
2                 20.2    1934      26     352  ...       4  20  30      1711
3                 29.1    1672      86     525  ...       1   7  12      1113
4                 22.9    1516     115     491  ...       2  23  14      1036
..                 ...     ...     ...     ...  ...     ...  ..  ..       ...
205               18.0     929      25     131  ...      31  27  36       933
206               28.9    1176       6      94  ...      57  77  51      1445
207               11.6     356      21      40  ...       4  26  13       491
208               15.1     601      22      99  ...       6  12  16       538
209               16.0     875      18     151  ...      14  24  16       828

                     Unnamed: 32_level_0  Pos
      Rec  Rec% Prog             Matches Pos1 Pos2
0    1186  93.3   35             Matches   MF
1    2315  97.5   38             Matches   MF
2    1630  95.3   45             Matches   MF
3    1055  94.8   26             Matches   MF
4     920  88.8   43             Matches   DF
..    ...   ...  ...                 ...  ...  ...
205   691  74.1  141             Matches   FW
206   923  63.9  257             Matches   FW
207   251  51.1   96             Matches   FW
208   410  76.2   57             Matches   MF
209   689  83.2   95             Matches   MF   FW

[210 rows x 34 columns]

In [3]:
data = {
  "BRO": {
    "BSN": { "W": 10, "L": 12 },
    "CHC": { "W": 15, "L": 7 },
    "CIN": { "W": 15, "L": 7 },
    "NYG": { "W": 14, "L": 8 },
    "PHI": { "W": 14, "L": 8 },
    "PIT": { "W": 15, "L": 7 },
    "STL": { "W": 11, "L": 11 }
  },

  "BSN": {
    "BRO": { "W": 12, "L": 10 },

    "CHC": { "W": 13, "L": 9 },

    "CIN": { "W": 13, "L": 9 },

    "NYG": { "W": 13, "L": 9 },

    "PHI": { "W": 14, "L": 8 },

    "PIT": { "W": 12, "L": 10 },

    "STL": { "W": 9, "L": 13 }
  },

  "CHC": {
    "BRO": { "W": 7, "L": 15 },

    "BSN": { "W": 9, "L": 13 },

    "CIN": { "W": 12, "L": 10 },

    "NYG": { "W": 7, "L": 15 },

    "PHI": { "W": 16, "L": 6 },

    "PIT": { "W": 8, "L": 14 },

    "STL": { "W": 10, "L": 12 }
  },

  "CIN": {
    "BRO": { "W": 7, "L": 15 },

    "BSN": { "W": 9, "L": 13 },

    "CHC": { "W": 10, "L": 12 },

    "NYG": { "W": 13, "L": 9 },

    "PHI": { "W": 13, "L": 9 },

    "PIT": { "W": 13, "L": 9 },

    "STL": { "W": 8, "L": 14 }
  },

  "NYG": {
    "BRO": { "W": 8, "L": 14 },

    "BSN": { "W": 9, "L": 13 },

    "CHC": { "W": 15, "L": 7 },

    "CIN": { "W": 9, "L": 13 },

    "PHI": { "W": 12, "L": 10 },

    "PIT": { "W": 15, "L": 7 },

    "STL": { "W": 13, "L": 9 }
  },

  "PHI": {
    "BRO": { "W": 8, "L": 14 },

    "BSN": { "W": 8, "L": 14 },

    "CHC": { "W": 6, "L": 16 },

    "CIN": { "W": 9, "L": 13 },

    "NYG": { "W": 10, "L": 12 },

    "PIT": { "W": 13, "L": 9 },

    "STL": { "W": 8, "L": 14 }
  },

  "PIT": {
    "BRO": { "W": 7, "L": 15 },

    "BSN": { "W": 10, "L": 12 },

    "CHC": { "W": 14, "L": 8 },

    "CIN": { "W": 9, "L": 13 },

    "NYG": { "W": 7, "L": 15 },

    "PHI": { "W": 9, "L": 13 },

    "STL": { "W": 6, "L": 16 }
  },

  "STL": {
    "BRO": { "W": 11, "L": 11 },

    "BSN": { "W": 13, "L": 9 },

    "CHC": { "W": 12, "L": 10 },

    "CIN": { "W": 14, "L": 8 },

    "NYG": { "W": 9, "L": 13 },

    "PHI": { "W": 14, "L": 8 },

    "PIT": { "W": 16, "L": 6 }
  }
}

In [19]:
table = []
for team in data:
    row = []
    scores = data.get(team)
    for s in scores:
        win = scores.get(s)['W']
        row.append(win)
    table.append(row)
table

[[10, 15, 15, 14, 14, 15, 11],
 [12, 13, 13, 13, 14, 12, 9],
 [7, 9, 12, 7, 16, 8, 10],
 [7, 9, 10, 13, 13, 13, 8],
 [8, 9, 15, 9, 12, 15, 13],
 [8, 8, 6, 9, 10, 13, 8],
 [7, 10, 14, 9, 7, 9, 6],
 [11, 13, 12, 14, 9, 14, 16]]